import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home({ quotes }) {
  const [quote, setQuote] = useState({});
  const [isClicked, setIsClicked] = useState(false);

  function randomQuoteGenerator() {
    const randomIndex = Math.floor(Math.random() * 1644);
    setQuote(quotes[randomIndex]);
    console.log(quotes[randomIndex]);
    setIsClicked(true);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Random Quote Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <p>Random Quotes for You</p>
        </div>

        <div className={styles.grid}>
          <button className={styles.btn} onClick={randomQuoteGenerator}>
            Generate Random Quote
          </button>
          {isClicked ? (
            <blockquote className={styles.code}>
              <p>{quote.text}</p>
              <cite>
                {isClicked && quote.author == null
                  ? "- Anonymous"
                  : "- " + quote.author}
              </cite>
            </blockquote>
          ) : (
            <p className={styles.tagline}>Wishing You A Wonderful Day!</p>
          )}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://type.fit/api/quotes");
  const quotes = await res.json();

  return {
    props: {
      quotes,
    },
  };
}
